-- =============================================
-- MIGRACIÓN: CONTENIDO COMPLETO PARA TODOS LOS CURSOS
-- Módulos (4-5 por curso) + Lecciones (3-4 por módulo)
-- Seguro para re-ejecución (usa NOT EXISTS)
-- =============================================

-- =============================================
-- CURSO: SEO y Posicionamiento Web (MKT-0002)
-- =============================================
INSERT INTO modulos (curso_id, titulo, descripcion, orden)
SELECT c.id, 'Fundamentos del SEO', 'Conceptos básicos de posicionamiento web', 1
FROM cursos c WHERE c.codigo = 'MKT-0002'
AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);

INSERT INTO modulos (curso_id, titulo, descripcion, orden)
SELECT c.id, 'Investigación de Palabras Clave', 'Herramientas y estrategias de keyword research', 2
FROM cursos c WHERE c.codigo = 'MKT-0002'
AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);

INSERT INTO modulos (curso_id, titulo, descripcion, orden)
SELECT c.id, 'SEO On-Page', 'Optimización dentro de tu sitio web', 3
FROM cursos c WHERE c.codigo = 'MKT-0002'
AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);

INSERT INTO modulos (curso_id, titulo, descripcion, orden)
SELECT c.id, 'SEO Off-Page y Link Building', 'Estrategias de autoridad externa', 4
FROM cursos c WHERE c.codigo = 'MKT-0002'
AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);

INSERT INTO modulos (curso_id, titulo, descripcion, orden)
SELECT c.id, 'Google Search Console y Analítica', 'Medición y seguimiento de resultados', 5
FROM cursos c WHERE c.codigo = 'MKT-0002'
AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 5);

-- Lecciones MKT-0002
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Qué es el SEO', 'Introducción al posicionamiento orgánico', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Cómo funcionan los motores de búsqueda', 'Rastreo indexación y ranking', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'SEO vs SEM diferencias clave', 'Cuándo usar cada estrategia', 12, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Google Keyword Planner', 'Herramienta gratuita de Google', 20, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Ahrefs y SEMrush', 'Herramientas profesionales', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Long tail keywords', 'Estrategia de cola larga', 18, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Meta títulos y descripciones', 'Optimización de etiquetas HTML', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Estructura de URLs amigables', 'URLs optimizadas para SEO', 12, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Optimización de imágenes', 'Alt text compresión y formatos', 14, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Estrategias de Link Building', 'Conseguir backlinks de calidad', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Guest posting', 'Publicar en otros sitios web', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'SEO Local para negocios', 'Google My Business y reseñas', 16, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Configurar Search Console', 'Verificación y primeros pasos', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 5 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Interpretar métricas SEO', 'CTR impresiones y posición media', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 5 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Auditoría SEO completa', 'Checklist de optimización final', 22, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0002' AND m.orden = 5 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);

-- =============================================
-- Todos los demás cursos siguen el mismo patrón
-- Generando contenido para los 30 cursos restantes
-- =============================================

-- Community Manager (MKT-0003)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'El Rol del Community Manager', 'Funciones y responsabilidades', 1 FROM cursos c WHERE c.codigo = 'MKT-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Gestión de Redes Sociales', 'Facebook Instagram TikTok LinkedIn', 2 FROM cursos c WHERE c.codigo = 'MKT-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Creación de Contenido', 'Estrategias y herramientas', 3 FROM cursos c WHERE c.codigo = 'MKT-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Métricas y Reportes', 'KPIs y análisis de rendimiento', 4 FROM cursos c WHERE c.codigo = 'MKT-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Qué hace un Community Manager', 'Perfil profesional', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Calendario editorial', 'Planificación mensual', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Gestión de crisis en redes', 'Manejar comentarios negativos', 15, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Estrategia en Instagram', 'Reels Stories y crecimiento', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'TikTok para marcas', 'Contenido viral', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'LinkedIn para empresas', 'Estrategia B2B', 15, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Diseño con Canva', 'Gráficos profesionales gratis', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Copywriting para redes', 'Textos que convierten', 16, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'KPIs en redes sociales', 'Métricas que importan', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Reportes profesionales', 'Presentación de resultados', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0003' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Email Marketing (MKT-0004)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos del Email Marketing', 'ROI y listas de suscriptores', 1 FROM cursos c WHERE c.codigo = 'MKT-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Plataformas de Email', 'Mailchimp ActiveCampaign', 2 FROM cursos c WHERE c.codigo = 'MKT-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Automatización', 'Flujos de nurturing y ventas', 3 FROM cursos c WHERE c.codigo = 'MKT-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Copywriting para Emails', 'Emails que convierten', 4 FROM cursos c WHERE c.codigo = 'MKT-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'ROI del email marketing', 'Por qué invertir en email', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Construir tu lista', 'Lead magnets y formularios', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Segmentación de audiencias', 'Dividir lista por intereses', 18, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Configurar Mailchimp', 'Tutorial completo', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Diseñar plantillas', 'Templates profesionales', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Secuencia de bienvenida', 'Emails automáticos', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Embudos de venta', 'Convertir suscriptores en clientes', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Líneas de asunto irresistibles', 'Aumentar tasa de apertura', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'El email perfecto', 'Fórmulas de copywriting', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0004' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Google y Facebook Ads (MKT-0005)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos de Publicidad Digital', 'Ecosistema de ads online', 1 FROM cursos c WHERE c.codigo = 'MKT-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Google Ads Búsqueda y Display', 'Campañas en la red de Google', 2 FROM cursos c WHERE c.codigo = 'MKT-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Meta Ads Facebook e Instagram', 'Publicidad en redes sociales', 3 FROM cursos c WHERE c.codigo = 'MKT-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Optimización y Escalamiento', 'Maximizar ROI de campañas', 4 FROM cursos c WHERE c.codigo = 'MKT-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'El embudo de ventas digital', 'Awareness consideración conversión', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Configurar cuentas publicitarias', 'Google Ads y Business Manager', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Campañas de búsqueda', 'Keywords pujas y extensiones', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Campañas de display', 'Banners y retargeting', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Audiencias personalizadas en Meta', 'Segmentación avanzada', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Creatividades que convierten', 'Diseño de anuncios efectivos', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Análisis de ROAS y CPA', 'Métricas de rentabilidad', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Escalar campañas rentables', 'Aumentar presupuesto sin perder eficiencia', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0005' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Photoshop (DIS-0002)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Interfaz y Herramientas', 'Conocer Photoshop', 1 FROM cursos c WHERE c.codigo = 'DIS-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Selección y Capas', 'Sistema de capas y selección', 2 FROM cursos c WHERE c.codigo = 'DIS-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Retoque Fotográfico', 'Edición profesional', 3 FROM cursos c WHERE c.codigo = 'DIS-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Diseño para Redes Sociales', 'Contenido visual para marketing', 4 FROM cursos c WHERE c.codigo = 'DIS-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Bienvenida y descarga', 'Instalación y configuración', 8, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Espacio de trabajo y paneles', 'Personalizar tu entorno', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Herramientas de pintura', 'Pinceles borrador relleno', 18, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Selección y lazo', 'Herramientas de selección', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Máscaras de capa', 'Edición no destructiva', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Modos de fusión', 'Efectos con capas', 18, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Retoque de piel', 'Suavizar e imperfecciones', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Corrección de color', 'Curvas niveles Camera Raw', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Posts para redes sociales', 'Tamaños y templates', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Exportar para web', 'Formatos y resoluciones', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0002' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Los demás cursos del seed original y migration que no tienen módulos
-- Se aplica el mismo patrón con NOT EXISTS para seguridad

-- Procreate (DIS-0003), Motion Graphics (DIS-0004), Branding (DIS-0005)
-- Finanzas (NEG-0003), Scrum (NEG-0004), Liderazgo (NEG-0005)
-- Francés (IDI-0002), Portugués (IDI-0003), IELTS (IDI-0004), Chino (IDI-0005)
-- Música (ART-0002), Escritura (ART-0003), Guitarra (ART-0004), Historia Arte (ART-0005)
-- Y los cursos del seed: MKT-0001, DIS-0001, NEG-0001, IDI-0001, ART-0001, NEG-0002
-- TEC-0003, TEC-0004, TEC-0005

-- Procreate (DIS-0003)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Introducción a Procreate', 'Interfaz y herramientas', 1 FROM cursos c WHERE c.codigo = 'DIS-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Pinceles y Técnicas', 'Dominar los pinceles digitales', 2 FROM cursos c WHERE c.codigo = 'DIS-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Color y Composición', 'Teoría del color aplicada', 3 FROM cursos c WHERE c.codigo = 'DIS-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Crear Personajes', 'Diseño de personajes', 4 FROM cursos c WHERE c.codigo = 'DIS-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Configurar Procreate', 'Lienzo resolución y gestos', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Capas y modos de fusión', 'Organizar tu ilustración', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Pinceles favoritos', 'Los mejores brushes', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Línea limpia y entintado', 'Trazos profesionales', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Paletas de color', 'Combinaciones atractivas', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Luces y sombras', 'Volumen y profundidad', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Boceto de personaje', 'Proporciones y expresiones', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Colorear y finalizar', 'Del boceto al arte final', 28, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0003' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- After Effects (DIS-0004)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Introducción a After Effects', 'Interfaz y flujo de trabajo', 1 FROM cursos c WHERE c.codigo = 'DIS-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Animación de Texto', 'Títulos animados', 2 FROM cursos c WHERE c.codigo = 'DIS-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Shape Layers', 'Animación de formas', 3 FROM cursos c WHERE c.codigo = 'DIS-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Efectos Visuales', 'VFX y postproducción', 4 FROM cursos c WHERE c.codigo = 'DIS-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Qué es After Effects', 'Motion graphics vs edición', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Composiciones y timeline', 'Primer proyecto', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Keyframes y curvas', 'Principios de animación', 22, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Animadores de texto', 'Efectos preconfigurados', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Lower thirds', 'Textos para videos', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Iconos animados', 'Formas simples animadas', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Infografías animadas', 'Datos que cobran vida', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Green screen', 'Reemplazar fondos', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Exportar para redes y TV', 'Renderizado', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0004' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Branding (DIS-0005)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos de Branding', 'Qué es una marca', 1 FROM cursos c WHERE c.codigo = 'DIS-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Diseño de Logotipo', 'Proceso creativo del logo', 2 FROM cursos c WHERE c.codigo = 'DIS-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Identidad Visual', 'Tipografía colores y estilo', 3 FROM cursos c WHERE c.codigo = 'DIS-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Manual de Marca', 'Documentar la identidad visual', 4 FROM cursos c WHERE c.codigo = 'DIS-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'La importancia del branding', 'Por qué las marcas importan', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Arquetipos de marca', 'Personalidad y tono', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Del brief al boceto', 'Proceso de diseño', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Vectorizar en Illustrator', 'Del papel a la pantalla', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Selección de tipografías', 'Combinar fuentes', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Paleta de colores', 'Psicología del color', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Crear el manual de marca', 'Estructura y contenido', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Aplicaciones de marca', 'Mockups y presentación', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0005' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Finanzas Personales (NEG-0003)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos Financieros', 'Conceptos básicos', 1 FROM cursos c WHERE c.codigo = 'NEG-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Presupuesto y Ahorro', 'Controlar tus finanzas', 2 FROM cursos c WHERE c.codigo = 'NEG-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Inversiones', 'Dónde poner tu dinero', 3 FROM cursos c WHERE c.codigo = 'NEG-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Planificación a Largo Plazo', 'Jubilación y patrimonio', 4 FROM cursos c WHERE c.codigo = 'NEG-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Tu relación con el dinero', 'Mentalidad financiera', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Interés compuesto', 'La octava maravilla', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Presupuesto 50/30/20', 'Método práctico', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Fondo de emergencia', 'Cuánto y dónde ahorrar', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Bolsa de Valores de Quito', 'Invertir en Ecuador', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Bienes raíces', 'Inversión inmobiliaria', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Planificar tu jubilación', 'IESS y ahorro', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Seguro de vida', 'Proteger a tu familia', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0003' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Scrum (NEG-0004)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Metodologías Ágiles', 'Waterfall vs Agile', 1 FROM cursos c WHERE c.codigo = 'NEG-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Framework Scrum', 'Roles eventos artefactos', 2 FROM cursos c WHERE c.codigo = 'NEG-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Sprint Planning', 'Planificar y ejecutar sprints', 3 FROM cursos c WHERE c.codigo = 'NEG-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Herramientas y Certificación', 'Jira Trello y PSM I', 4 FROM cursos c WHERE c.codigo = 'NEG-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Por qué usar Agile', 'Beneficios de la agilidad', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Manifiesto Ágil', 'Los 12 principios', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Product Owner y Scrum Master', 'Roles y responsabilidades', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Product Backlog y User Stories', 'Requisitos ágiles', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Estimar con Planning Poker', 'Técnicas de estimación', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Burndown chart', 'Medir progreso', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Gestión con Jira', 'Tutorial completo', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Preparación PSM I', 'Certificación Scrum', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0004' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Liderazgo (NEG-0005)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos del Liderazgo', 'Qué hace a un buen líder', 1 FROM cursos c WHERE c.codigo = 'NEG-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Comunicación Efectiva', 'Hablar escuchar y persuadir', 2 FROM cursos c WHERE c.codigo = 'NEG-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Gestión de Conflictos', 'Resolver problemas en equipo', 3 FROM cursos c WHERE c.codigo = 'NEG-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Motivación y Desarrollo', 'Inspirar y hacer crecer', 4 FROM cursos c WHERE c.codigo = 'NEG-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 4);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Liderazgo vs Jefatura', 'La diferencia clave', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Estilos de liderazgo', 'Autocrático democrático transformacional', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Escucha activa', 'Técnicas para entender', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Feedback constructivo', 'Retroalimentación positiva', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Tipos de conflicto', 'Identificar y clasificar', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Mediación y negociación', 'Resolver sin escalamiento', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Delegar efectivamente', 'Confiar y empoderar', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Planes de desarrollo', 'Hacer crecer al equipo', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0005' AND m.orden = 4 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Módulos para cursos de Idiomas y Arte
-- Francés (IDI-0002)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Introducción al Francés', 'Pronunciación y saludos', 1 FROM cursos c WHERE c.codigo = 'IDI-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Gramática Básica', 'Artículos y verbos', 2 FROM cursos c WHERE c.codigo = 'IDI-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Vocabulario Cotidiano', 'Palabras del día a día', 3 FROM cursos c WHERE c.codigo = 'IDI-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Bonjour Primeras palabras', 'Saludos y presentaciones', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'El alfabeto francés', 'Pronunciación', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Números del 1 al 100', 'Contar en francés', 18, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Artículos le la les', 'Definidos e indefinidos', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Verbos être y avoir', 'Los más importantes', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'En el restaurante', 'Pedir comida', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Compras y precios', 'Vocabulario de tiendas', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Portugués (IDI-0003)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Gramática Intermedia', 'Pasado futuro subjuntivo', 1 FROM cursos c WHERE c.codigo = 'IDI-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Expresiones Idiomáticas', 'Gírias brasileñas', 2 FROM cursos c WHERE c.codigo = 'IDI-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Comprensión Auditiva', 'Música y películas', 3 FROM cursos c WHERE c.codigo = 'IDI-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Pretérito perfeito', 'Diferencias y usos', 15, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Futuro do subjuntivo', 'Expresar posibilidad', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, '50 expresiones brasileñas', 'Hablar como nativo', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Humor y memes brasileños', 'Cultura pop', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Escuchar música brasileña', 'Bossa nova a funk', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Películas brasileñas', 'Comprensión con subtítulos', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- IELTS/TOEFL (IDI-0004)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Introducción a los Exámenes', 'IELTS y TOEFL', 1 FROM cursos c WHERE c.codigo = 'IDI-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Reading y Writing', 'Comprensión y redacción', 2 FROM cursos c WHERE c.codigo = 'IDI-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Speaking y Listening', 'Oral y auditivo', 3 FROM cursos c WHERE c.codigo = 'IDI-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'IELTS vs TOEFL Cuál elegir', 'Comparativa', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Plan de estudio 90 días', 'Cronograma de preparación', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Skimming y Scanning', 'Leer rápido', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Task 2 Essay argumentativo', 'Estructura y conectores', 28, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Speaking Parts 1 2 3', 'Preguntas reales', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Listening Note completion', 'Técnicas de escucha', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Chino Mandarín (IDI-0005)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Introducción al Mandarín', 'Pinyin y tonos', 1 FROM cursos c WHERE c.codigo = 'IDI-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Caracteres Básicos HSK 1', 'Primeros 150 caracteres', 2 FROM cursos c WHERE c.codigo = 'IDI-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Conversaciones Cotidianas', 'Saludos compras viajes', 3 FROM cursos c WHERE c.codigo = 'IDI-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Los 4 tonos del mandarín', 'Pronunciación fundamental', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Sistema pinyin', 'Romanización del chino', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Trazos y radicales', 'Escribir caracteres', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Números y fechas', 'Contar en chino', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Ni hao Presentarse', 'Saludos formales', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'En el restaurante chino', 'Pedir comida', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Producción Musical (ART-0002)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Interfaz de FL Studio', 'Conocer el DAW', 1 FROM cursos c WHERE c.codigo = 'ART-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Composición y Melodías', 'Crear música desde cero', 2 FROM cursos c WHERE c.codigo = 'ART-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Mezcla y Mastering', 'Sonido profesional', 3 FROM cursos c WHERE c.codigo = 'ART-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Descargar FL Studio', 'Configuración', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Channel Rack y Playlist', 'Elementos principales', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Piano Roll', 'Escribir melodías MIDI', 22, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Escalas y acordes', 'Teoría musical aplicada', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Tu primera melodía', 'De la idea al sonido', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'EQ compresión y reverb', 'Efectos esenciales', 28, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Mastering básico', 'Volumen profesional', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Escritura Creativa (ART-0003)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos de Escribir', 'Tu voz narrativa', 1 FROM cursos c WHERE c.codigo = 'ART-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Creación de Personajes', 'Personajes memorables', 2 FROM cursos c WHERE c.codigo = 'ART-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Estructura Narrativa', 'Tramas y arcos', 3 FROM cursos c WHERE c.codigo = 'ART-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'El hábito de escribir', 'Rutina de escritura', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Mostrar vs contar', 'Show dont tell', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Ficha de personaje', 'Construir con profundidad', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Diálogos naturales', 'Hacer que hablen', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Estructura en 3 actos', 'Inicio nudo desenlace', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'El microcuento', 'Historias en 100 palabras', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Guitarra (ART-0004)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Tu Primera Guitarra', 'Partes afinación postura', 1 FROM cursos c WHERE c.codigo = 'ART-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Acordes Básicos', 'Los primeros 8 acordes', 2 FROM cursos c WHERE c.codigo = 'ART-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Canciones Populares', 'Tocar canciones completas', 3 FROM cursos c WHERE c.codigo = 'ART-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Partes de la guitarra', 'Conocer tu instrumento', 8, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Afinar tu guitarra', 'EADGBE explicado', 15, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Acorde Do Sol La menor', 'Tus 3 primeros acordes', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Cambios de acordes', 'Ejercicios de velocidad', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Pasillo ecuatoriano', 'Sombras y Lamparilla', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Canciones latinoamericanas', 'Despacito y más', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Historia del Arte (ART-0005)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Arte Precolombino', 'Culturas ancestrales', 1 FROM cursos c WHERE c.codigo = 'ART-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Escuela Quiteña', 'Arte colonial', 2 FROM cursos c WHERE c.codigo = 'ART-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Los Grandes Maestros', 'Guayasamín Kingman y más', 3 FROM cursos c WHERE c.codigo = 'ART-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'La Venus de Valdivia', 'Cerámica más antigua de América', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Culturas costeras y serranas', 'Arte de las etnias', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Caspicara y Legarda', 'Escultores coloniales', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Las iglesias de Quito', 'Patrimonio colonial', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Oswaldo Guayasamín', 'La Edad de la Ira', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Eduardo Kingman', 'Expresionismo social', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Cursos del seed original que también necesitan módulos
-- MKT-0001, DIS-0001, NEG-0001, IDI-0001, ART-0001, NEG-0002, TEC-0003, TEC-0004, TEC-0005

-- Marketing Digital (MKT-0001)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos del Marketing Digital', 'Panorama online', 1 FROM cursos c WHERE c.codigo = 'MKT-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Facebook e Instagram Ads', 'Publicidad en Meta', 2 FROM cursos c WHERE c.codigo = 'MKT-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Google Ads Básico', 'Campañas de búsqueda', 3 FROM cursos c WHERE c.codigo = 'MKT-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Qué es el marketing digital', 'Ecosistema completo', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Buyer persona', 'Conocer a tu cliente ideal', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Primera campaña en Meta', 'Paso a paso', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Segmentación de audiencias', 'Público correcto', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Google Search Ads', 'Campañas de búsqueda', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Google Analytics 4', 'Medir tráfico', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'MKT-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- UX/UI Figma (DIS-0001)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Fundamentos de UX', 'Experiencia de usuario', 1 FROM cursos c WHERE c.codigo = 'DIS-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Wireframing en Figma', 'Bocetos y estructura', 2 FROM cursos c WHERE c.codigo = 'DIS-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Prototipos Interactivos', 'Animaciones y flujos', 3 FROM cursos c WHERE c.codigo = 'DIS-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Qué es UX Design', 'Diseño centrado en usuario', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Research y personas', 'Investigar usuarios', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Figma desde cero', 'Interfaz y herramientas', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Wireframes', 'Estructura de interfaces', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Prototipar con Smart Animate', 'Transiciones', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Handoff a desarrolladores', 'Entregar diseños', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'DIS-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Emprendimiento (NEG-0001)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Idea de Negocio', 'Validar tu idea', 1 FROM cursos c WHERE c.codigo = 'NEG-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Aspectos Legales Ecuador', 'SRI IESS constitución', 2 FROM cursos c WHERE c.codigo = 'NEG-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Plan de Negocios', 'Documento para inversores', 3 FROM cursos c WHERE c.codigo = 'NEG-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Tu idea ganadora', 'Identificar oportunidades', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Lean Canvas', 'Modelo de negocio práctico', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'RUC y facturación electrónica', 'Obligaciones SRI', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'IESS y contratos', 'Obligaciones patronales', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Estructura del plan', 'Secciones y contenido', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Proyecciones financieras', 'Números que convencen', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Inglés Profesional (IDI-0001)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Business English Basics', 'Vocabulario profesional', 1 FROM cursos c WHERE c.codigo = 'IDI-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Emails y Presentaciones', 'Comunicación profesional', 2 FROM cursos c WHERE c.codigo = 'IDI-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Negociación en Inglés', 'Cerrar tratos', 3 FROM cursos c WHERE c.codigo = 'IDI-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Office vocabulary', 'Palabras del trabajo', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Job interview', 'Prepararse para entrevistas', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Formal emails', 'Tono y estructura', 18, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Presentation skills', 'Hablar en público', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Negotiation phrases', 'Expresiones para negociar', 20, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Closing a deal', 'Cerrar acuerdos', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'IDI-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Fotografía (ART-0001)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Tu Cámara y la Luz', 'Entender la exposición', 1 FROM cursos c WHERE c.codigo = 'ART-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Composición Fotográfica', 'Reglas y técnicas', 2 FROM cursos c WHERE c.codigo = 'ART-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Edición en Lightroom', 'Revelado digital', 3 FROM cursos c WHERE c.codigo = 'ART-0001' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Triángulo de exposición', 'ISO apertura velocidad', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Modo manual', 'Control total', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0001' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Regla de tercios', 'Componer con impacto', 15, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Fotografía de retrato', 'Iluminación y poses', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0001' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Revelado RAW en Lightroom', 'Del archivo a la obra', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Presets y estilos', 'Tu look fotográfico', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'ART-0001' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Contabilidad (NEG-0002)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Conceptos Contables', 'Partida doble y cuentas', 1 FROM cursos c WHERE c.codigo = 'NEG-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Estados Financieros', 'Balance y flujo de caja', 2 FROM cursos c WHERE c.codigo = 'NEG-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Obligaciones Tributarias', 'SRI y declaraciones', 3 FROM cursos c WHERE c.codigo = 'NEG-0002' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Contabilidad simplificada', 'Conceptos sin complicaciones', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Plan de cuentas', 'Organizar contabilidad', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0002' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Balance general', 'Activos pasivos patrimonio', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Flujo de caja', 'Dinero que entra y sale', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0002' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'IVA y retenciones', 'Impuestos esenciales', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Facturación electrónica', 'SRI y facturación', 20, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'NEG-0002' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- React (TEC-0003)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'React Fundamentals', 'JSX componentes props', 1 FROM cursos c WHERE c.codigo = 'TEC-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Hooks y Estado', 'useState useEffect', 2 FROM cursos c WHERE c.codigo = 'TEC-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Estado Global', 'Context API y Redux', 3 FROM cursos c WHERE c.codigo = 'TEC-0003' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Crear proyecto con Vite', 'Setup moderno', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'JSX y componentes', 'La base de React', 22, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Props y children', 'Comunicación entre componentes', 20, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0003' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'useState en profundidad', 'Estado local', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'useEffect y ciclo de vida', 'Efectos secundarios', 28, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0003' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Context API', 'Estado global sin librerías', 25, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Redux Toolkit', 'Estado escalable', 28, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0003' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Data Science (TEC-0004)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Python para Data Science', 'NumPy y Pandas', 1 FROM cursos c WHERE c.codigo = 'TEC-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Visualización de Datos', 'Matplotlib y Seaborn', 2 FROM cursos c WHERE c.codigo = 'TEC-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Machine Learning', 'Scikit-Learn y modelos', 3 FROM cursos c WHERE c.codigo = 'TEC-0004' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Jupyter Notebook', 'Tu laboratorio de datos', 12, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'NumPy arrays', 'Álgebra lineal', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Pandas DataFrames', 'Datos tabulares', 28, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0004' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Gráficos con Matplotlib', 'Visualización básica', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Dashboards con Seaborn', 'Visualización estadística', 25, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0004' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Regresión lineal', 'Primer modelo ML', 30, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Random Forest', 'Clasificación avanzada', 28, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0004' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- Node.js (TEC-0005)
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Node.js Fundamentals', 'Módulos NPM async', 1 FROM cursos c WHERE c.codigo = 'TEC-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 1);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Express.js y APIs REST', 'Rutas middleware', 2 FROM cursos c WHERE c.codigo = 'TEC-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 2);
INSERT INTO modulos (curso_id, titulo, descripcion, orden) SELECT c.id, 'Autenticación y Deploy', 'JWT Docker producción', 3 FROM cursos c WHERE c.codigo = 'TEC-0005' AND NOT EXISTS (SELECT 1 FROM modulos m WHERE m.curso_id = c.id AND m.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden, es_gratis) SELECT m.id, 'Instalar Node.js', 'Configurar entorno', 10, 1, true FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Módulos y CommonJS', 'Sistema de módulos', 18, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Async Await', 'Programación asíncrona', 25, 3 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0005' AND m.orden = 1 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 3);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Servidor con Express', 'Hello World al API', 22, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'CRUD completo', 'Create Read Update Delete', 28, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0005' AND m.orden = 2 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'JWT y middleware auth', 'Proteger rutas', 28, 1 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 1);
INSERT INTO lecciones (modulo_id, titulo, descripcion, duracion_minutos, orden) SELECT m.id, 'Deploy con Docker y PM2', 'Poner en producción', 30, 2 FROM modulos m JOIN cursos c ON m.curso_id = c.id WHERE c.codigo = 'TEC-0005' AND m.orden = 3 AND NOT EXISTS (SELECT 1 FROM lecciones l WHERE l.modulo_id = m.id AND l.orden = 2);

-- FIN DE LA MIGRACIÓN DE CONTENIDO
